# Generated by Django 3.2.6 on 2022-01-15 08:05

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('note', models.TextField(max_length=500)),
                ('create_at', models.DateTimeField(default=datetime.datetime(2022, 1, 15, 8, 5, 29, 601781))),
                ('deadline', models.DateTimeField(default=datetime.datetime(2022, 1, 15, 8, 5, 29, 601781))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.user')),
            ],
        ),
    ]
