# Generated by Django 3.2.6 on 2022-01-16 04:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_auto_20220116_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 16, 4, 50, 33, 483361, tzinfo=utc)),
        ),
    ]
